### ISSUE TITLE
How does TubeMQ support the use of the Java 7 environment?

### ISSUE THREAD

**Issue by gosonzhang** [Tencent/TubeMQ#73]
Considering that the business environment using TubeMQ is java 7 and does not allow upgrades, it's a better support method to adjust the je version to a lower version than 7.3.7, such as 6.1.5.

- - - - - 

考虑到使用TubeMQ的商业环境是Java 7，并且不允许升级情况，如果业务需要使用TubeMQ,将je版本调整为低于7.3.7（例如6.1.5）的版本是一种比较好的支持方法。

**Comment by gosonzhang** [comment]
see https://github.com/Tencent/TubeMQ/pull/72

**Comment by gosonzhang** [comment]
@TisonKun I found that in the jdk 1.7 environment, compiling the entire project will report the following error, can help to see how to deal with it?
- - - - - - - - - - - - 
我发现在jdk 1.7环境，编译整个工程会报如下这个错误，能帮忙看看怎么处理吗？

```
[INFO] --- maven-checkstyle-plugin:3.1.0:check (checkstyle) @ tubemq ---
[WARNING] Error injecting: org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo
java.lang.TypeNotPresentException: Type org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo not present
        at org.eclipse.sisu.space.URLClassSpace.loadClass(URLClassSpace.java:147)
        at org.eclipse.sisu.space.NamedClass.load(NamedClass.java:46)
        at org.eclipse.sisu.space.AbstractDeferredClass.get(AbstractDeferredClass.java:48)
        at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:81)
        at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdap
```
