### ISSUE TITLE
 Tubemq client throws an exception when stopping the consumer.

### ISSUE THREAD

**Issue by Libeibei1990** [Tencent/TubeMQ#99]
java.lang.InterruptedException: sleep Interrupted
        at java.lang.Thread.sleep(Native Method)
        at com.tencent.tubemq.corebase.utils.ThreadUtils.sleep(ThreadUtils.java:128)
        at com.tencent.tubemq.client.consumer.RmtDataCache.pushSelect(RmtDataCache.java:241)
        at com.tencent.tubemq.client.consumer.BaseMessageConsumer.pushSelectPartition(BaseMessageConsumer.java:713)
        at com.tencent.tubemq.client.consumer.MessageFetchManager$FetchTaskWorker.run(MessageFetchManager.java:180)
        at java.lang.Thread.run(Thread.java:745)

**Comment by gosonzhang** [comment]
Ok, I get it now, thanks！
